#!/usr/bin/env python
import sys

DATABASE_FILE = "database.txt"

# 1 arguement command
if len(sys.argv) < 2:
    print("Not enough arguements")
    sys.exit()

cmds = str(sys.argv)
cmd = sys.argv[1].lower()


if cmd == 'help':
    print("list: list all cmds stored ")
    print("-s cmd: Saves the cmd")
    print("-i cmd: Information on cmd")
    sys.exit()




#  2 arguement commands
if len(sys.argv) < 3:
    print("Not enough arguements")
    sys.exit()

cmds = str(sys.argv)
flag = sys.argv[1].lower()
cmd = sys.argv[2]

#Saves the cmd
if flag == '-s':

    answer = raw_input("Description:?\n")
    
    if len(answer) > 1:
        #save with description
        f = open(DADTAASE_FILE, 'a')
        f.write(cmd)
        f.write(":")
        f.write(answer)
        f.write("\n")
        f.close()
    else:
        #save no description
        f = open(DADTAASE_FILE, 'a')
        f.write(cmd)
        f.write(":\n")
        f.close()
    
    sys.exit()

#Information on command
if flag == "-i":
    f = open(DATABASE_FILE, 'r')
    text = f.read().split('\n')
    
    for line in text:
        lineArr = line.split(":")

        if cmd == lineArr[0]:
            if len(lineArr[1]) > 1:
                print(lineArr[1])
            break;
    
    sys.exit()  